version: 0.2

phases:
  # install:
  #     commands:
  #         - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  #         - unzip awscliv2.zip
  #         - sudo ./aws/install
  pre_build:
    commands:
      - echo "Pre Build started  on `date`"
  build:
    commands:
      - echo "Build started  on `date`"
      - pwd
      - echo "Build Dockerfile"
      - echo "Tag image - tag nginx:latest 428855609275.dkr.ecr.us-east-1.amazonaws.com/toluna-lab:latest"
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Login to repo"
      - echo "Push image to repo - push 428855609275.dkr.ecr.us-east-1.amazonaws.com/toluna-lab:latest"
